app: cloud-monitor-manager
serve:
  port: 8080
  debug: true
#  read_timeout:
#  write_timeout:
db:
  url: root:123456@(127.0.0.1:3306)/hawkeye?charset=utf8mb4&parseTime=True&loc=Local
  dialect: mysql
  max_idle_connes: 10
  max_open_connes: 100

logger:
  data_log_prefix: ../logs/
  group: cloud-manager
  max_size:
  max_backups:
  max_age:
  compress:

