app: cloud-monitor-manager
serve:
  port: 8081
  debug: true
#  read_timeout:
#  write_timeout:
db:
  url: (127.0.0.1:3306)/hawkeye_region?charset=utf8mb4&parseTime=True&loc=Local
  dialect: mysql
  max_idle_connes: 10
  max_open_connes: 100
  username: root

logger:
  data_log_prefix: /logs/
  service_name: cloud-monitor-region
  max_size:
  max_backups:
  max_age:
  compress:

http:
  connection_time_out: 3
  read_time_out: 3
  write_time_out: 3

rocketmq:
  name-server: 127.0.0.1:9876
  broker-addr: 127.0.0.1:10911
  contactTopic: contactTopic
  instanceTopic: hawkeye-instance
  ruleTopic: rule

prometheus:
  url: http://localhost:52617/api/v1
  query: /query?query=
  queryRange: /query_range?query=

common:
  env: local
  nk: http://aopesb.dev001.intranet.cecloudcs.com/cestc
  tenantUrl: ''
  smsCenterPath: http://aopesb.dev001.intranet.cecloudcs.com/cestc?appId=600006&format=json&method=CESTC_UNHQ_saveMessageOperate
  hawkeyeCenterPath: ''
  hasNoticeModel: true
  regionName: 'local'
  ecs-inner-gateway: http://ecs-gateway.inner.dev001.intranet.cecloudcs.com

redis:
  addr: 'localhost:6379'
  password: ''