definitions:
  controllers.AlarmInstanceRegionVO:
    properties:
      bindNum:
        description: "*\n\t * 已绑定实例数"
        type: integer
      total:
        type: integer
    type: object
  global.Resp:
    properties:
      allowRetry:
        type: boolean
      errorArgs:
        items: {}
        type: array
      errorCode:
        type: string
      errorMsg:
        type: string
      module: {}
      success:
        type: boolean
    type: object
  vo.PageVO:
    properties:
      current:
        type: integer
      records:
        items: {}
        type: array
      size:
        type: integer
      total:
        type: integer
    type: object
info:
  contact: {}
paths:
  /hawkeye/instance/page:
    get:
      consumes:
      - application/json
      description: GetInstanceNumByRegion
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.AlarmInstanceRegionVO'
      summary: GetInstanceNumByRegion
      tags:
      - InstanceCtl
  /hawkeye/monitorProduct/getById:
    get:
      consumes:
      - application/json
      description: GetById
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: GetById
      tags:
      - MonitorProductCtl
swagger: "2.0"
