UPDATE t_monitor_item SET metrics_linux = 'sum by(instance)(ecs_memory_MemTotal_bytes{$INSTANCE}) - (sum by(instance)(ecs_memory_MemFree_bytes{$INSTANCE}) + sum by(instance)(ecs_memory_Cached_bytes{$INSTANCE}))' WHERE metric_name = 'ecs_memory_used';
UPDATE t_monitor_item SET metrics_linux = '100 * ((sum by(instance)(ecs_memory_MemTotal_bytes{$INSTANCE}) - (sum by(instance)(ecs_memory_MemFree_bytes{}) + sum by(instance)(ecs_memory_Cached_bytes{}))) / sum by(instance)(ecs_memory_MemTotal_bytes{}))' WHERE metric_name = 'ecs_memory_usage';
UPDATE t_monitor_item SET metrics_linux = 'sum by(instance)(ecs_memory_MemTotal_bytes{$INSTANCE}) - (sum by(instance)(ecs_memory_MemFree_bytes{$INSTANCE}) + sum by(instance)(ecs_memory_Cached_bytes{$INSTANCE}))' WHERE metric_name = 'bms_memory_used';
UPDATE t_monitor_item SET metrics_linux = '100 * ((sum by(instance)(ecs_memory_MemTotal_bytes{$INSTANCE}) - (sum by(instance)(ecs_memory_MemFree_bytes{}) + sum by(instance)(ecs_memory_Cached_bytes{}))) / sum by(instance)(ecs_memory_MemTotal_bytes{}))' WHERE metric_name = 'bms_memory_usage';
UPDATE t_monitor_item SET metrics_linux = 'sum by(instance)(ecs_memory_MemTotal_bytes{$INSTANCE}) - (sum by(instance)(ecs_memory_MemFree_bytes{$INSTANCE}) + sum by(instance)(ecs_memory_Cached_bytes{$INSTANCE}))' WHERE metric_name = 'ebms_memory_used';
UPDATE t_monitor_item SET metrics_linux = '100 * ((sum by(instance)(ecs_memory_MemTotal_bytes{$INSTANCE}) - (sum by(instance)(ecs_memory_MemFree_bytes{}) + sum by(instance)(ecs_memory_Cached_bytes{}))) / sum by(instance)(ecs_memory_MemTotal_bytes{}))' WHERE metric_name = 'ebms_memory_usage';

INSERT INTO t_monitor_item (biz_id, product_biz_id, name, metric_name, labels, metrics_linux, metrics_windows, statistics, unit, frequency, type, is_display, status, description, create_user, create_time, show_expression, display) VALUES ('155', '11', '集群磁盘使用量', 'kafka_logdirsusage_partition_usage', 'instance', 'sum by (instance,instanceType) (kafka_logdirsusage_partition_usage{$INSTANCE})', null, null, 'Byte', null, null, '1', '1', null, null, null, null, 'chart,rule');

INSERT INTO t_monitor_item (biz_id, product_biz_id, name, metric_name, labels, metrics_linux, metrics_windows, statistics, unit, frequency, type, is_display, status, description, create_user, create_time, show_expression, display) VALUES ('234', '1', '(基础)GPU使用率', 'ecs_base_gpu_seconds', 'instance', 'sum by (instance,instanceType) (ecs_base_gpu_seconds{$INSTANCE})', null, null, '%', null, '1', '1', '1', null, null, null, null, 'chart,rule,scaling');
INSERT INTO t_monitor_item (biz_id, product_biz_id, name, metric_name, labels, metrics_linux, metrics_windows, statistics, unit, frequency, type, is_display, status, description, create_user, create_time, show_expression, display) VALUES ('235', '1', '(基础)GPU显存总量', 'ecs_base_gpu_memory_total', 'instance', 'sum by (instance,instanceType) (ecs_base_gpu_memory_total{$INSTANCE})', null, null, 'MB', null, '1', '1', '1', null, null, null, null, 'chart,rule');
INSERT INTO t_monitor_item (biz_id, product_biz_id, name, metric_name, labels, metrics_linux, metrics_windows, statistics, unit, frequency, type, is_display, status, description, create_user, create_time, show_expression, display) VALUES ('236', '1', '(基础)GPU显存已使用量', 'ecs_base_gpu_memory_usage', 'instance', 'sum by (instance,instanceType) (ecs_base_gpu_memory_usage{$INSTANCE})', null, null, 'MB', null, '1', '1', '1', null, null, null, null, 'chart,rule');
