INSERT INTO t_monitor_product (biz_id, name, status, description, create_user, create_time, route, cron, host, page_url, abbreviation, sort, monitor_type, iam_page_url) VALUES ('16', '云工作负载保护CWP', '1', 'cwp', null, null, '/productmonitoring/cwp', '0 0 0/1 * * ?', 'http://product-ecs-ecs-manage.product-ecs', '/noauth/ecs/PageList', 'cwp', '16', '云产品监控', '/compute/ecs/instance/cbc/pageList');

INSERT INTO t_monitor_item (biz_id, product_biz_id, name, metric_name, labels, metrics_linux, metrics_windows, statistics, unit, frequency, type, is_display, status, description, create_user, create_time, show_expression, display) VALUES ('239', '16', 'Agent CPU使用率', 'cwpagent_cpu_usage_percent', 'instance,agentVersion', 'sum by(instance,instanceType,agentVersion)(cwpagent_cpu_used_percent{$INSTANCE})', null, null, '%', null, '1', '1', '1', 'ECS上，Agent进程的CPU使用率', null, now(), null, 'chart,rule');
INSERT INTO t_monitor_item (biz_id, product_biz_id, name, metric_name, labels, metrics_linux, metrics_windows, statistics, unit, frequency, type, is_display, status, description, create_user, create_time, show_expression, display) VALUES ('240', '16', 'Agent 内存使用量', 'cwpagent_mem_used_MBytes', 'instance,agentVersion', 'sum by(instance,instanceType,agentVersion)(cwpagent_mem_used_MBytes{$INSTANCE})', null, null, 'MBytes', null, '1', '1', '1', 'ECS上，Agent进程的内存使用量', null, now(), null, 'chart,rule');
INSERT INTO t_monitor_item (biz_id, product_biz_id, name, metric_name, labels, metrics_linux, metrics_windows, statistics, unit, frequency, type, is_display, status, description, create_user, create_time, show_expression, display) VALUES ('241', '16', 'Agent 内存使用率', 'cwpagent_mem_used_percent', 'instance,agentVersion', 'sum by(instance,instanceType,agentVersion)(cwpagent_mem_used_percent{$INSTANCE})', null, null, '%', null, '1', '1', '1', 'ECS上，Agent进程的内存使用率', null, now(), null, 'chart,rule');
INSERT INTO t_monitor_item (biz_id, product_biz_id, name, metric_name, labels, metrics_linux, metrics_windows, statistics, unit, frequency, type, is_display, status, description, create_user, create_time, show_expression, display) VALUES ('242', '16', 'Agent 目录已用存储量', 'cwpagent_disk_used_MBytes', 'instance,agentVersion', 'sum by(instance,instanceType,agentVersion)(cwpagent_disk_used_MBytes{$INSTANCE})', null, null, 'MBytes', null, '1', '1', '1', 'CWP Agent目录已用存储量', null, now(), null, 'chart,rule');
INSERT INTO t_monitor_item (biz_id, product_biz_id, name, metric_name, labels, metrics_linux, metrics_windows, statistics, unit, frequency, type, is_display, status, description, create_user, create_time, show_expression, display) VALUES ('243', '16', 'Agent 所在挂载点存储总量', 'cwpagent_disk_mount_total_MBytes', 'instance,agentVersion', 'sum by(instance,instanceType,agentVersion)(cwpagent_disk_mount_total_MBytes{$INSTANCE})', null, null, 'MBytes', null, '1', '1', '1', 'CWP Agent所在挂载点存储总量', null, now(), null, 'chart,rule');
INSERT INTO t_monitor_item (biz_id, product_biz_id, name, metric_name, labels, metrics_linux, metrics_windows, statistics, unit, frequency, type, is_display, status, description, create_user, create_time, show_expression, display) VALUES ('244', '16', 'Agent 所在挂载点剩余存储量', 'cwpagent_disk_mount_free_MBytes', 'instance,agentVersion', 'sum by(instance,instanceType,agentVersion)(cwpagent_disk_mount_free_MBytes{$INSTANCE})', null, null, 'MBytes', null, '1', '1', '1', 'CWP Agent所在挂载点剩余存储量', null, now(), null, 'chart,rule');
INSERT INTO t_monitor_item (biz_id, product_biz_id, name, metric_name, labels, metrics_linux, metrics_windows, statistics, unit, frequency, type, is_display, status, description, create_user, create_time, show_expression, display) VALUES ('245', '16', 'Agent 打开文件句柄数', 'cwpagent_files_opend_num', 'instance,agentVersion', 'sum by(instance,instanceType,agentVersion)(cwpagent_files_opend_num{$INSTANCE})', null, null, '个', null, '1', '1', '1', 'CWP Agent进程打开的文件句柄数', null, now(), null, 'chart,rule');
INSERT INTO t_monitor_item (biz_id, product_biz_id, name, metric_name, labels, metrics_linux, metrics_windows, statistics, unit, frequency, type, is_display, status, description, create_user, create_time, show_expression, display) VALUES ('246', '16', 'Agent 运行任务总数量', 'cwpagent_state_running_total_jobs', 'instance,agentVersion', 'sum by(instance,instanceType,agentVersion)(cwpagent_state_running_total_jobs{$INSTANCE})', null, null, '个', null, '1', '1', '1', 'CWP Agent 运行task数量', null, now(), null, 'chart,rule');
INSERT INTO t_monitor_item (biz_id, product_biz_id, name, metric_name, labels, metrics_linux, metrics_windows, statistics, unit, frequency, type, is_display, status, description, create_user, create_time, show_expression, display) VALUES ('247', '16', 'Agent 运行长期任务数量', 'cwpagent_state_persistent_job_cnt', 'instance,agentVersion', 'sum by(instance,instanceType,agentVersion)(cwpagent_state_persistent_job_cnt{$INSTANCE})', null, null, '个', null, '1', '1', '1', 'CWP Agent 运行长期任务数量', null, now(), null, 'chart,rule');
INSERT INTO t_monitor_item (biz_id, product_biz_id, name, metric_name, labels, metrics_linux, metrics_windows, statistics, unit, frequency, type, is_display, status, description, create_user, create_time, show_expression, display) VALUES ('248', '16', 'Agent 运行实时任务数量', 'cwpagent_state_realtime_job_cnt', 'instance,agentVersion', 'sum by(instance,instanceType,agentVersion)(cwpagent_state_realtime_job_cnt{$INSTANCE})', null, null, '个', null, '1', '1', '1', 'CWP Agent 运行实时任务数量', null, now(), null, 'chart,rule');
INSERT INTO t_monitor_item (biz_id, product_biz_id, name, metric_name, labels, metrics_linux, metrics_windows, statistics, unit, frequency, type, is_display, status, description, create_user, create_time, show_expression, display) VALUES ('249', '16', 'Agent 采集进程日志数量', 'cwpagent_state_total_event', 'instance,agentVersion', 'sum by(instance,instanceType,agentVersion)(cwpagent_state_total_event{$INSTANCE})', null, null, '条/min', null, '1', '1', '1', 'CWP Agent 累计采集进程日志数量', null, now(), null, 'chart,rule');
INSERT INTO t_monitor_item (biz_id, product_biz_id, name, metric_name, labels, metrics_linux, metrics_windows, statistics, unit, frequency, type, is_display, status, description, create_user, create_time, show_expression, display) VALUES ('250', '16', 'Agent 丢弃进程日志数量', 'cwpagent_state_drop_event', 'instance,agentVersion', 'sum by(instance,instanceType,agentVersion)(cwpagent_state_drop_event{$INSTANCE})', null, null, '条/min', null, '1', '1', '1', 'CWP Agent 累计丢弃进程日志数量', null, now(), null, 'chart,rule');
INSERT INTO t_monitor_item (biz_id, product_biz_id, name, metric_name, labels, metrics_linux, metrics_windows, statistics, unit, frequency, type, is_display, status, description, create_user, create_time, show_expression, display) VALUES ('251', '16', 'Agent 采集进程日志速率', 'cwpagent_state_event_rate', 'instance,agentVersion', 'sum by(instance,instanceType,agentVersion)(cwpagent_state_event_rate{$INSTANCE})', null, null, '条/s', null, '1', '1', '1', 'CWP Agent 采集进程日志速率(条/s)', null, now(), null, 'chart,rule');
INSERT INTO t_monitor_item (biz_id, product_biz_id, name, metric_name, labels, metrics_linux, metrics_windows, statistics, unit, frequency, type, is_display, status, description, create_user, create_time, show_expression, display) VALUES ('252', '16', 'Agent 检测文件数量', 'cwpagent_state_total_upload_sample', 'instance,agentVersion', 'sum by(instance,instanceType,agentVersion)(cwpagent_state_total_upload_sample{$INSTANCE})', null, null, '个/min', null, '1', '1', '1', 'CWP Agent 检测文件数量', null, now(), null, 'chart,rule');
INSERT INTO t_monitor_item (biz_id, product_biz_id, name, metric_name, labels, metrics_linux, metrics_windows, statistics, unit, frequency, type, is_display, status, description, create_user, create_time, show_expression, display) VALUES ('253', '16', 'Agent 检测文件失败数量', 'cwpagent_state_fail_upload_sample', 'instance,agentVersion', 'sum by(instance,instanceType,agentVersion)(cwpagent_state_fail_upload_sample{$INSTANCE})', null, null, '个/min', null, '1', '1', '1', 'CWP Agent 检测文件失败数量', null, now(), null, 'chart,rule');
INSERT INTO t_monitor_item (biz_id, product_biz_id, name, metric_name, labels, metrics_linux, metrics_windows, statistics, unit, frequency, type, is_display, status, description, create_user, create_time, show_expression, display) VALUES ('254', '16', 'Agent 检测文件大小', 'cwpagent_state_total_upload_size', 'instance,agentVersion', 'sum by(instance,instanceType,agentVersion)(cwpagent_state_total_upload_size{$INSTANCE})', null, null, 'Bytes/min', null, '1', '1', '1', 'CWP Agent 检测文件大小', null, now(), null, 'chart,rule');
INSERT INTO t_monitor_item (biz_id, product_biz_id, name, metric_name, labels, metrics_linux, metrics_windows, statistics, unit, frequency, type, is_display, status, description, create_user, create_time, show_expression, display) VALUES ('255', '16', 'Agent 上报运行日志字节数', 'cwpagent_network_logserver_flow_size', 'instance,agentVersion', 'sum by(instance,instanceType,agentVersion)(cwpagent_network_logserver_flow_size{$INSTANCE})', null, null, 'Bytes/min', null, '1', '1', '1', 'Agent 上报运行日志字节数', null, now(), null, 'chart,rule');
INSERT INTO t_monitor_item (biz_id, product_biz_id, name, metric_name, labels, metrics_linux, metrics_windows, statistics, unit, frequency, type, is_display, status, description, create_user, create_time, show_expression, display) VALUES ('256', '16', 'Agent 域名解析失败次数', 'cwpagent_state_dns_error_cnt', 'instance,agentVersion', 'sum by(instance,instanceType,agentVersion)(cwpagent_state_dns_error_cnt{$INSTANCE})', null, null, '次/min', null, '1', '1', '1', 'CWP Agent 域名解析失败次数', null, now(), null, 'chart,rule');
INSERT INTO t_monitor_item (biz_id, product_biz_id, name, metric_name, labels, metrics_linux, metrics_windows, statistics, unit, frequency, type, is_display, status, description, create_user, create_time, show_expression, display) VALUES ('257', '16', 'Agent RPC网络错误次数', 'cwpagent_state_rpc_error_cnt', 'instance,agentVersion', 'sum by(instance,instanceType,agentVersion)(cwpagent_state_rpc_error_cnt{$INSTANCE})', null, null, '个/min', null, '1', '1', '1', 'CWP Agent RPC网络错误次数', null, now(), null, 'chart,rule');
INSERT INTO t_monitor_item (biz_id, product_biz_id, name, metric_name, labels, metrics_linux, metrics_windows, statistics, unit, frequency, type, is_display, status, description, create_user, create_time, show_expression, display) VALUES ('258', '16', 'Agent 全部累计重启次数', 'cwpagent_state_agent_restart_cnt', 'instance,agentVersion', 'sum by(instance,instanceType,agentVersion)(cwpagent_state_agent_restart_cnt{$INSTANCE})', null, null, '次', null, '1', '1', '1', 'CWP Agent 全部累计重启次数', null, now(), null, 'chart');
INSERT INTO t_monitor_item (biz_id, product_biz_id, name, metric_name, labels, metrics_linux, metrics_windows, statistics, unit, frequency, type, is_display, status, description, create_user, create_time, show_expression, display) VALUES ('259', '16', 'Agent 5分钟内累计重启次数', 'cwpagent_state_agent_restart_cnt_5min', 'instance,agentVersion', 'floor(sum by(instance,instanceType,agentVersion)(increase(cwpagent_state_agent_restart_cnt{$INSTANCE}[5m])))', null, null, '次/5min', null, '1', '1', '1', 'CWP Agent 5分钟内累计重启次数', null, now(), null, 'chart,rule');

UPDATE t_monitor_item SET metrics_linux = 'rate(ecs_disk_read_time_seconds_total{$INSTANCE}[5m]) / clamp_min(rate(ecs_disk_reads_completed_total{$INSTANCE}[5m]),1) * 1000' WHERE metric_name = 'ecs_disk_read_time';
UPDATE t_monitor_item SET metrics_linux = 'rate(ecs_disk_write_time_seconds_total{$INSTANCE}[5m]) / clamp_min(rate(ecs_disk_writes_completed_total{$INSTANCE}[5m]),1) * 1000' WHERE metric_name = 'ecs_disk_write_time';

UPDATE t_monitor_item SET metrics_linux = '100 * ((sum by(instance)(ecs_memory_MemTotal_bytes{$INSTANCE}) - (sum by(instance)(ecs_memory_MemFree_bytes{$INSTANCE}) + sum by(instance)(ecs_memory_Cached_bytes{$INSTANCE}))) / sum by(instance)(ecs_memory_MemTotal_bytes{$INSTANCE}))' WHERE metric_name = 'ecs_memory_usage';
UPDATE t_monitor_item SET metrics_linux = '100 * ((sum by(instance)(ecs_memory_MemTotal_bytes{$INSTANCE}) - (sum by(instance)(ecs_memory_MemFree_bytes{$INSTANCE}) + sum by(instance)(ecs_memory_Cached_bytes{$INSTANCE}))) / sum by(instance)(ecs_memory_MemTotal_bytes{$INSTANCE}))' WHERE metric_name = 'bms_memory_usage';
UPDATE t_monitor_item SET metrics_linux = '100 * ((sum by(instance)(ecs_memory_MemTotal_bytes{$INSTANCE}) - (sum by(instance)(ecs_memory_MemFree_bytes{$INSTANCE}) + sum by(instance)(ecs_memory_Cached_bytes{$INSTANCE}))) / sum by(instance)(ecs_memory_MemTotal_bytes{$INSTANCE}))' WHERE metric_name = 'ebms_memory_usage';
