UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_slave_io{$INSTANCE})' WHERE biz_id = '86';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_slave_sql{$INSTANCE})' WHERE biz_id = '87';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_slave_seconds_behind_master{$INSTANCE})' WHERE biz_id = '88';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_active_connections{$INSTANCE})' WHERE biz_id = '89';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_current_connection_percent{$INSTANCE})' WHERE biz_id = '90';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_qps{$INSTANCE})' WHERE biz_id = '91';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_tps{$INSTANCE})' WHERE biz_id = '92';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_select_ps{$INSTANCE})' WHERE biz_id = '93';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_update_ps{$INSTANCE})' WHERE biz_id = '94';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_insert_ps{$INSTANCE})' WHERE biz_id = '95';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_delete_ps{$INSTANCE})' WHERE biz_id = '96';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_cpu_usage{$INSTANCE})' WHERE biz_id = '97';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_mem_usage{$INSTANCE})' WHERE biz_id = '98';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_disk_usage{$INSTANCE})' WHERE biz_id = '99';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_innodb_select_ps{$INSTANCE})' WHERE biz_id = '100';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_innodb_update_ps{$INSTANCE})' WHERE biz_id = '101';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_innodb_insert_ps{$INSTANCE})' WHERE biz_id = '102';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_innodb_delete_ps{$INSTANCE})' WHERE biz_id = '103';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_innodb_cache_hit_rate{$INSTANCE})' WHERE biz_id = '104';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_innodb_reads_ps{$INSTANCE})' WHERE biz_id = '105';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_innodb_writes_ps{$INSTANCE})' WHERE biz_id = '106';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_innodb_buffer_pool_pages_dirty{$INSTANCE})' WHERE biz_id = '107';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_innodb_buffer_pool_bytes_dirty{$INSTANCE})' WHERE biz_id = '108';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_innodb_log_waits{$INSTANCE})' WHERE biz_id = '109';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_binlog_cache_disk_use{$INSTANCE})' WHERE biz_id = '110';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_slow_queries_per_min{$INSTANCE})' WHERE biz_id = '111';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_long_query_count{$INSTANCE})' WHERE biz_id = '112';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_long_query_alert_count{$INSTANCE})' WHERE biz_id = '113';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_exec_statememt_frequency{$INSTANCE})' WHERE biz_id = '114';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_read_frequency{$INSTANCE})' WHERE biz_id = '115';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_write_frequency{$INSTANCE})' WHERE biz_id = '116';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_top_statememt_avg_exec_time{$INSTANCE})' WHERE biz_id = '117';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_top_statememt_exec_err_rate{$INSTANCE})' WHERE biz_id = '118';
UPDATE t_monitor_item SET metrics_linux = 'sum by (instance)(mysql_current_cons_num{$INSTANCE})' WHERE biz_id = '119';

DELETE FROM t_monitor_item WHERE biz_id IN ('226','227','228','229','230','231','232','233');
DELETE FROM t_monitor_product WHERE abbreviation = 'nat-e';

ALTER TABLE t_monitor_product DROP COLUMN iam_page_url;

DROP INDEX alarm_rule_id ON `t_alarm_rule_resource_rel`;
